"""The ladder's report, generated rather than typed.

`docs/ladder.md` is written by this module from the numbers a run produced, on the same principle
as `Simulation/docs/calibration.md`: a table of results that someone re-types by hand goes stale
the first time the code changes, and a stale measurement is worse than none.

Three things the reader has to know to read the table, so they are printed next to it:

  * **A win rate is field-relative.** Twelve seats play a round robin against each other, so a
    rung's win rate depends on who else is in the league. Removing a weak rung raises everyone
    else's. Points per week is the portable number; win rate is only comparable *within* one run.
  * **A slot left empty and a slot filled by a player who did not dress are different errors.**
    Only rung 1 makes the second one in quantity, and one ratio would hide that.
  * **Decision efficiency is realized points over the hindsight-optimal lineup from the same
    roster.** It separates decision quality from roster quality, which a season total cannot.
"""

import logging

import pandas as pd

import paths

log = logging.getLogger("report")

PREAMBLE = """# The baseline ladder

Generated by `ladder.py` -- do not edit by hand.

Section 16 of the build plan defines four rungs and says the modelling stack has to clear the
third of them decisively or it is not paying for itself. This is what the harness measures.

Phase 1 replays **the real {season} season**: outcomes are the actual stat lines, not samples, so
there is no Monte Carlo noise in these numbers. One mixed twelve-team league, four clones of each
rung, double round robin over {weeks} matchup weeks.

"""

NOTES = """
## Reading the table

**A win rate is field-relative.** All rungs sit in one league and play each other, so a rung's
win rate depends on the company. `points_per_week` is the portable number; compare win rates only
within a single run.

**`empty_slot_nights` and `wasted_slot_nights` are different failures.** The first is a slot with
nobody in it; the second is a slot filled by a player who did not dress. Rung 1 makes the second
one about a thousand times a season, which is precisely the cost of never looking at the lineup.

**`decision_efficiency`** is realized points divided by the best legal lineup the same roster
could have started that night, known only in hindsight. It answers "how much did this manager
leave on the table", separately from "how good was the roster".

**The structural fact behind every number here:** only about half the NHL plays on a given night,
so a sixteen-man roster has roughly **seven** startable players against twelve active slots. No
manager in this league ever fills its lineup. That is why filling slots dominates upgrading them,
and it is the arithmetic section 15 rests on.
"""


def write(report: dict, season: str, weeks: int, path=None) -> str:
    """Render one run's results to markdown and return the text."""
    path = path or (paths.ensure(paths.DOCS_DIR) / "ladder.md")
    lines = [PREAMBLE.format(season=season, weeks=weeks)]

    columns = ["rung", "strategy", "win_rate", "points_per_week", "games_started_rate",
               "decision_efficiency", "empty_slot_nights", "wasted_slot_nights", "moves_spent",
               "forced_drops", "move_hit_rate", "realized_gain_per_move", "rentals",
               "rental_hit_rate", "rental_gain"]
    headers = ["rung", "strategy", "win rate", "points / week", "games started",
               "decision eff.", "empty slots", "wasted slots", "moves", "forced drops",
               "move hit rate", "gain / move", "rentals", "rental hit", "rental gain"]

    for scoreset_name, payload in report["results"].items():
        table = pd.DataFrame(payload["by_rung"]).sort_values("rung")
        lines.append(f"## {scoreset_name}\n")
        lines.append("| " + " | ".join(headers) + " |")
        lines.append("|" + "|".join(["---"] * len(headers)) + "|")
        for row in table.itertuples():
            values = [str(getattr(row, c, "")) if c in ("rung", "strategy")
                      else f"{getattr(row, c, float('nan')):.3f}" for c in columns]
            lines.append("| " + " | ".join(values) + " |")
        lines.append("")
        lines.append(_verdict(table, pd.DataFrame(payload["by_seat"])))
        lines.append("")

    lines.append(NOTES)
    text = "\n".join(lines)
    path.write_text(text, encoding="utf-8")
    log.info("-> %s", path)
    return text


def paired_difference(seats: pd.DataFrame, higher: int, lower: int):
    """(mean, standard error) of a rung-vs-rung gap, paired inside each league instance.

    Paired, because every rung in a run shares one free-agent pool and one schedule: comparing the
    two pooled means throws away the pairing and overstates the error. Reported with the error
    because a gap without one invites exactly the mistake this harness already made once -- an
    ablation put rung 4 twenty-three points ahead of rung 3, and it was the field composition
    talking rather than the strategy.
    """
    if seats.empty or "replication" not in seats:
        return None, None
    seats = seats.assign(pts_wk=seats["points"] / seats["weeks"])
    pivot = seats.pivot_table(index="replication", columns="rung", values="pts_wk")
    if higher not in pivot or lower not in pivot:
        return None, None
    delta = (pivot[higher] - pivot[lower]).dropna()
    if len(delta) < 2:
        return float(delta.mean()) if len(delta) else None, None
    return float(delta.mean()), float(delta.std() / (len(delta) ** 0.5))


def _significance(mean, se) -> str:
    if mean is None or se is None or se == 0:
        return ""
    if abs(mean) > 2 * se:
        return f" ({mean:+.1f} +/- {se:.1f}, clear of the noise)"
    return (f" ({mean:+.1f} +/- {se:.1f}, **not distinguishable from zero** -- the gap is smaller "
            f"than the spread across seats)")


def _verdict(table: pd.DataFrame, seats: pd.DataFrame = None) -> str:
    """State what the rungs did to each other, in points per week, without decoration."""
    by_rung = table.set_index("rung")
    seats = seats if seats is not None else pd.DataFrame()
    out = []
    if 1 in by_rung.index and 2 in by_rung.index:
        gain = by_rung.loc[2, "points_per_week"] - by_rung.loc[1, "points_per_week"]
        out.append(f"Attention alone (rung 2 over rung 1) is worth **{gain:+.1f} points a week**, "
                   f"and it costs no transactions at all.")
    if 2 in by_rung.index and 3 in by_rung.index:
        gain = by_rung.loc[3, "points_per_week"] - by_rung.loc[2, "points_per_week"]
        wins = by_rung.loc[3, "win_rate"] - by_rung.loc[2, "win_rate"]
        verb = "buys" if gain > 0 else "costs"
        out.append(f"The seven-move acquisition budget (rung 3 over rung 2) {verb} "
                   f"**{abs(gain):.1f} points a week** at "
                   f"{by_rung.loc[3, 'moves_spent']:.0f} moves spent.")
        # Points and won weeks can disagree, and when they do that is the head-to-head format
        # talking rather than noise: what a week pays out is a win, not a margin.
        if (gain > 0) != (wins > 0) and abs(wins) > 0.005:
            direction = "more" if wins > 0 else "fewer"
            out.append(f"Note the disagreement: it wins **{direction}** matchups "
                       f"({by_rung.loc[3, 'win_rate']:.3f} against "
                       f"{by_rung.loc[2, 'win_rate']:.3f}) than its points total implies. In a "
                       f"head-to-head league the margin is discarded every week, so where a "
                       f"strategy's points land matters as much as how many there are.")
    if 3 in by_rung.index and 4 in by_rung.index:
        gain = by_rung.loc[4, "points_per_week"] - by_rung.loc[3, "points_per_week"]
        mean, se = paired_difference(seats, 4, 3)
        verdict = ("**clears it**" if (mean is not None and se and mean > 2 * se)
                   else "**does not clear it**")
        out.append(f"The modelling stack (rung 4 over rung 3) is worth **{gain:+.1f} points a "
                   f"week**{_significance(mean, se)}. Section 16 asks whether it clears rung 3 "
                   f"decisively: it {verdict}.")
        mean2, se2 = paired_difference(seats, 4, 2)
        if mean2 is not None:
            out.append(f"Against rung 2, which never touches the wire, rung 4 is "
                       f"{mean2:+.1f}{'' if se2 is None else f' +/- {se2:.1f}'} points a week.")
    # Section 9's add/drop arms. Rung 6 is rung 4's lineup with no moves at all, so the gap from it
    # to rung 5 is exactly what the transactions are worth.
    for higher, lower, label in ((5, 6, "The add/drop rule against never moving (rung 5 over 6)"),
                                 (5, 4, "The add/drop rule against rung 4's (rung 5 over 4)"),
                                 (5, 2, "Rung 5 against rung 2, which never touches the wire"),
                                 (6, 2, "Holding with the full lineup against rung 2 (6 over 2)"),
                                 # Section 10: rung 7 is rung 5 plus streaming, so 7 over 5 is
                                 # what the rentals are worth and nothing else.
                                 (7, 5, "Streaming on top of the upgrades (rung 7 over 5)"),
                                 (7, 6, "The orchestrator against never moving (rung 7 over 6)"),
                                 (7, 2, "Rung 7 against rung 2")):
        if higher in by_rung.index and lower in by_rung.index:
            mean, se = paired_difference(seats, higher, lower)
            if mean is not None:
                out.append(f"{label}: **{mean:+.1f} points a week**{_significance(mean, se)}.")
    # Section 9 step 2: a twin rung (r + 10) is rung r drafting by value over replacement, so the
    # paired gap is what the draft board is worth with the in-season manager held fixed.
    for twin in sorted(r for r in by_rung.index if r > 10 and r - 10 in by_rung.index):
        mean, se = paired_difference(seats, twin, twin - 10)
        if mean is not None:
            out.append(f"Drafting by value over replacement, in-season manager held at rung "
                       f"{twin - 10} (rung {twin} over {twin - 10}): **{mean:+.1f} points a "
                       f"week**{_significance(mean, se)}.")
    return " ".join(out)
