#!/usr/bin/env python
"""Generates the committed model cards from the run's own artefacts.

Hand-written cards rot the moment a model is refit, so these are rendered from
`reports/training_*.json`, `reports/metrics_*.json` and `reports/dispersion.json` instead --
nothing here is typed by a person except the target notes in `targets.py`.

Usage:
    python modelcards.py --variant B
"""

import argparse
import json

import paths
import targets as targets_module


def parse_args():
    parser = argparse.ArgumentParser(description="Render the model cards")
    parser.add_argument("--variant", choices=("A", "B"), default="B")
    parser.add_argument("--season", default="2025-26", help="The scored holdout season to describe")
    return parser.parse_args()


def read(name):
    path = paths.REPORTS_DIR / name
    return json.loads(path.read_text(encoding="utf-8")) if path.exists() else {}


def table(rows, headers):
    lines = ["| " + " | ".join(headers) + " |",
             "| " + " | ".join("---" for _ in headers) + " |"]
    lines += ["| " + " | ".join(str(c) for c in row) + " |" for row in rows]
    return "\n".join(lines)


def render(variant, season="2025-26"):
    # training_<variant>.json is the deployment build in models/. With none (variant A has no
    # deployment build), the scored build's own summary describes the only boosters there are.
    training = read(f"training_{variant}.json") or read(f"training_{variant}_{season}.json")
    metrics = read(f"metrics_{variant}_{season}.json")
    dispersion = read(f"dispersion_{season}.json")
    if not training or not metrics:
        raise SystemExit(f"run train.py / evaluate.py --variant {variant} first")

    by_target = {record["target"]: record for record in training["models"]}
    deployed = ", ".join(training["train_seasons"])
    scored_on = training.get("holdout_season") or metrics.get("holdout_season", "2025-26")
    scored_train = " + ".join(training["train_seasons"] if training.get("holdout_season")
                              else metrics.get("train_seasons", ["2023-24", "2024-25"]))
    same_build = training.get("holdout_season") is not None

    # Every section that reports a number says which build produced it, at the number --
    # a reader who scrolls straight to a table should not have to rely on having seen the
    # header first. Kept to one line, since it repeats under every heading; the full
    # explanation lives once at the top.
    if same_build:
        measured = (f"*Trained on {scored_train}, scored on held-out {scored_on} "
                    f"— the deployed boosters.*")
    else:
        measured = (f"*Trained on {scored_train}, scored on held-out {scored_on} "
                    f"— **not** the deployed boosters (see the note at the top).*")
    built = f"*The deployed boosters: trained on {' + '.join(training['train_seasons'])}.*"
    out = [
        f"# Skater projection models -- variant {variant}",
        "",
        f"Generated by `modelcards.py` from the run's own artefacts. The **deployed** "
        f"boosters (`models/<the season they predict>/{variant}/`) are trained on {deployed.replace(', ', ' + ')} "
        f"(early stop from "
        f"{training['early_stop_cutoff']}), {training['features']} features.",
        "",
    ]
    if training.get("holdout_season"):
        out += [f"Scored on {training['holdout_season']}: {metrics['played_rows']:,} played "
                f"rows of {metrics['holdout_rows']:,} candidates. Everything below describes "
                "these same models.", ""]
    else:
        out += ["> **The accuracy figures below are not from these boosters.** This is a "
                "deployment build with nothing held back, so it produces no metrics. The "
                f"numbers come from the last scored build -- trained on {scored_train}, "
                f"scored on {scored_on} -- which shares this "
                "architecture and feature set but saw one season less. Treat them as the "
                "best available estimate, not a measurement of what is shipping.", ""]
    out += [
        "These models project **stats**, not fantasy points -- no scoring system is assumed "
        "anywhere in this folder. Composite figures below appear only for scoring files that "
        "were passed to `evaluate.py --weights`.",
        "",
        "## Accuracy against the two naive baselines",
        "",
        measured,
        "",
    ]

    rows = []
    for category in ("shots", "hits", "blocks", "assists", "goals", "pim"):
        entry = metrics.get(category)
        if not entry:
            continue
        model = entry["model"]
        baseline_keys = [k for k in entry if k.startswith("baseline_")]
        best = min((entry[k]["mae"] for k in baseline_keys), default=float("nan"))
        rows.append([
            f"`{category}`",
            f"{model['mean_actual']:.3f}",
            f"{model['mean_predicted']:.3f}",
            f"{model['mae']:.3f}",
            f"{best:.3f}",
            f"{model['spearman']:.3f}",
            f"{entry.get('crps', float('nan')):.3f}",
            f"{entry.get('pit', {}).get('deviation', float('nan')):.3f}",
        ])
    out += [table(rows, ["target", "mean actual", "mean predicted", "MAE", "best baseline MAE",
                         "Spearman", "CRPS", "PIT deviation"]), ""]

    plays = metrics.get("plays", {})
    if plays:
        out += [
            "## P(plays)", "", measured, "",
            f"AUC {plays['auc']:.4f}, Brier {plays['brier']:.4f}, log loss "
            f"{plays['log_loss']:.4f} against a base rate of {plays['base_rate']:.3f}. "
            "Reliability by decile of predicted probability:", "",
            table([[r["bin"], f"{r['n']:,}", r["predicted"], r["observed"]]
                   for r in plays["reliability"]],
                  ["predicted bin", "n", "mean predicted", "observed rate"]), "",
        ]

    toi_rows = []
    for name in ("toi", "ev_toi", "pp_toi"):
        entry = metrics.get(name, {}).get("model")
        if entry:
            toi_rows.append([f"`{name}`", f"{entry['mean_actual']:.0f}s",
                             f"{entry['mae']:.1f}s", f"{entry['rmse']:.1f}s",
                             f"{entry['spearman']:.3f}"])
    if toi_rows:
        out += ["## Ice time", "", measured, "",
                table(toi_rows, ["target", "mean actual", "MAE", "RMSE", "Spearman"]), ""]

    for name, entry in (metrics.get("composite") or {}).items():
        model = entry["model"]
        out += [f"## Under `{name}` scoring", "", measured, "",
                (entry.get("description") or "").strip(), "",
                "Weights: " + ", ".join(f"`{k}` {v:g}" for k, v in entry["weights"].items())
                + ".", "",
                f"MAE {model['mae']:.3f} on a mean of {model['mean_actual']:.2f} points per "
                f"game, Spearman {model['spearman']:.3f}, top-100 start/sit capture "
                f"{entry['start_sit_capture_top100']:.3f} (the share of each day's best-100 "
                "points the model's own best 100 actually collected).", ""]
        baseline_rows = [[key.replace("baseline_", ""), f"{entry[key]['mae']:.3f}"]
                         for key in entry if key.startswith("baseline_")]
        if baseline_rows:
            out += [table(baseline_rows, ["baseline", "MAE"]), ""]

    walk = read(f"metrics_walkforward_{variant}_{season}.json")
    if walk:
        wf = (walk.get("composite") or {})
        out += ["## Walk-forward -- the honesty check", "", measured, "",
                "Refit monthly on an expanding window across the holdout season, which is how "
                "the season simulator will actually consume these models. It buys little on "
                "accuracy and helps mainly with level -- tracking the season's own rates "
                "narrows the categories that drifted (see the bias column) -- so the single "
                "fit stays the default.", ""]
        walk_rows = []
        for category in ("shots", "hits", "blocks", "assists", "goals", "pim"):
            entry = walk.get(category)
            single = metrics.get(category)
            if entry and single:
                def bias(m):
                    return 100 * (m["mean_predicted"] / m["mean_actual"] - 1)
                walk_rows.append([f"`{category}`",
                                  f"{bias(single['model']):+.1f}% -> {bias(entry['model']):+.1f}%",
                                  f"{entry['model']['mae']:.3f}",
                                  f"{single['model']['mae']:.3f}",
                                  f"{entry.get('pit', {}).get('deviation', float('nan')):.3f}"])
        if walk_rows:
            out += [table(walk_rows, ["target", "bias, single -> walk-forward",
                                      "walk-forward MAE", "single-fit MAE",
                                      "PIT deviation"]), ""]

    cross = metrics.get("cross_features")
    if cross:
        out += ["## The live-feed bound", "", measured, "",
                f"The same boosters scored on variant {cross['features_variant']}'s holdout "
                f"features. `plays` AUC falls to {cross['plays_auc']:.4f}; the category "
                "projections barely move. That is the expected shape -- knowing tonight's "
                "lineup settles whether a player dresses, not how many shots he takes once "
                "he does.", ""]
        rows = [[f"`{c}`", f"{m['mae']:.3f}", f"{m['spearman']:.3f}"]
                for c, m in (cross.get("per_category") or {}).items() if m]
        if rows:
            out += [table(rows, ["category", "MAE", "Spearman"]), ""]

    if dispersion:
        out += ["## Dispersion handed to the Monte Carlo layer", "", measured, "",
                f"`{dispersion['parameterization']}`, fit by maximum likelihood on the "
                "holdout. The shared game-quality variance is the Gamma multiplier's "
                f"variance: **{dispersion['game_quality']['gamma_variance']}**.", "",
                "`Var(Y) = E[Var(Y|mu)] + Var(mu)`, so the observed column is the sum of "
                "the last two, not something the NB column should match on its own.", "",
                table([[f"`{name}`", entry["theta"], entry["mean_lambda"],
                        entry["observed_variance"], entry["nb_implied_variance"],
                        entry.get("lambda_variance", "-"),
                        entry.get("reconciliation_gap", "-")]
                       for name, entry in dispersion["categories"].items()],
                      ["category", "theta", "mean lambda", "observed variance",
                       "NB conditional variance", "Var(lambda)", "gap"]), ""]

    out += ["## Per-model detail", "", built, ""]
    for target in targets_module.PIPELINE:
        record = by_target.get(target.name)
        if not record:
            continue
        out += [f"### `{target.name}`", "",
                f"{target.note}", "",
                f"- objective `{record['objective']}`"
                + (f", offset `log({record['offset']})` with a mean-matching intercept of "
                   f"{record['offset_intercept']:+.4f}" if record["offset"] else "")
                + f", fit on {record['fit_rows']:,} rows ({record['rows']})",
                f"- {record['best_iteration']} trees, {record['seconds']}s, early-stop "
                + ", ".join(f"{k} {v:.4f}" for k, v in record["early_stop_metric"].items()),
                "- top features by gain: "
                + ", ".join(f"`{f['feature']}` {f['gain_share']:.1%}"
                            for f in record["top_features"][:6]),
                ""]

    return "\n".join(out)


def main():
    args = parse_args()
    paths.ensure(paths.DOCS_DIR)
    path = paths.DOCS_DIR / f"model-cards-{args.variant}.md"
    path.write_text(render(args.variant), encoding="utf-8", newline="\n")
    print(f"wrote docs/{path.name}")


if __name__ == "__main__":
    main()
